# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Resume
    url: about/
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
  - parent: Projects
    url: live-stream/
    name: Live-Stream
    weight: 31
  - parent: Projects
    url: 5g-testbed/
    name: 5G-Testbed
    weight: 32
  - parent: Projects
    url: emotional/
    name: Emotional-Analysis
    weight: 33
  - name: Focus Areas
    url: focus/
    weight: 40
  - parent: Focus Areas
    name: Network-Virtualization
    url: network-virtualization/
    weight: 41
  - parent: Focus Areas
    name: Cloud
    url: cloud/
    weight: 42
  - name: Learning Hub
    url: learning-hub/
    weight: 50
  - parent: Learning Hub
    name: All
    url: all/
    weight: 51
  - parent: Learning Hub
    name: Cloud
    url: cloud-hub/
    weight: 52
  - parent: Learning Hub
    name: Container-Orchestration
    url: container-orchestration-hub/
    weight: 53
  - parent: Learning Hub
    name: Network-Virtualization
    url: network-virtualization-hub/
    weight: 54
  - parent: Learning Hub
    name: DevOps & Automation
    url: devops-automation-hub/
    weight: 55
  - name: Contact
    url: contact/
    weight: 100
  
